// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_P7ElRSPoRwH6weSLPdfio26LPTBGsL0',
    appId: '1:226270398107:web:bb76e09dbc6c093299e83e',
    messagingSenderId: '226270398107',
    projectId: 'attendance-app-ccc41',
    authDomain: 'attendance-app-ccc41.firebaseapp.com',
    storageBucket: 'attendance-app-ccc41.appspot.com',
    measurementId: 'G-36CTMS4H55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT2GIsAdl6w5UhFSZY2kbjmLyYHVEkG9Q',
    appId: '1:226270398107:android:61c2568fbdf476d199e83e',
    messagingSenderId: '226270398107',
    projectId: 'attendance-app-ccc41',
    storageBucket: 'attendance-app-ccc41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1qdzatquUGkjjc1h26QZPus32n6gzdUE',
    appId: '1:226270398107:ios:2d51c683ea5736e099e83e',
    messagingSenderId: '226270398107',
    projectId: 'attendance-app-ccc41',
    storageBucket: 'attendance-app-ccc41.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1qdzatquUGkjjc1h26QZPus32n6gzdUE',
    appId: '1:226270398107:ios:95e7a57c669da43899e83e',
    messagingSenderId: '226270398107',
    projectId: 'attendance-app-ccc41',
    storageBucket: 'attendance-app-ccc41.appspot.com',
    iosBundleId: 'com.example.attendanceApp.RunnerTests',
  );
}
